### ISSUE TITLE
Can't send images in a chat session, but audio and video files work.

### ISSUE THREAD

**Issue by War004** [googleapis/python-genai#48]
When I try to send an image with the text prompt into the chat session it gives me this error consistently.
```
File "...../test.py", line 110, in main
    response = await chat.send_message(["What do you think of this?",media_file])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...../apikeys/lib/python3.11/site-packages/google/genai/chats.py", line 188, in send_message
    response = await self._modules.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...../apikeys/lib/python3.11/site-packages/google/genai/models.py", line 5293, in generate_content
    response = await self._generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...../apikeys/lib/python3.11/site-packages/google/genai/models.py", line 4565, in _generate_content
    response_dict = await self.api_client.async_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...../apikeys/lib/python3.11/site-packages/google/genai/_api_client.py", line 358, in async_request
    result = await self._async_request(http_request=http_request, stream=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...../apikeys/lib/python3.11/site-packages/google/genai/_api_client.py", line 304, in _async_request
    return await asyncio.to_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...../apikeys/lib/python3.11/site-packages/google/genai/_api_client.py", line 263, in _request
    return self._request_unauthorized(http_request, stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...../apikeys/lib/python3.11/site-packages/google/genai/_api_client.py", line 285, in _request_unauthorized
    errors.APIError.raise_for_response(response)
  File "...../apikeys/lib/python3.11/site-packages/google/genai/errors.py", line 100, in raise_for_response
    raise ClientError(status_code, response)
google.genai.errors.ClientError: 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Request contains an invalid argument.', 'status': 'INVALID_ARGUMENT'}}
```

#### Environment details

  - Programming language: Python
  - OS: Linux (Debian 6.1.119-1, kernel 6.1.0-28-cloud-amd64)
  - Language runtime version: Python 3.11.2
  - Package version: google-genai 0.3.0

#### Steps to reproduce

  1. Initialize a chat session (Async or normal)
  2. Send an image file in the chat session. (Files or Local upload)
#### Additional details 
* The error comes in both async or normal chat session. 
* Whether the method for attaching the image is through local upload or using the files. It gives the same error.
* **If I send a video file or an audio file using local upload or files, it doesn't give me an error and request is completed successfully.**

Code used:
```
#Configuration Block
from google import genai
from google.genai import types
from google.genai import files

GOOGLE_API_KEY=os.getenv('GOOGLE_API_KEY')
client = genai.Client(api_key=GOOGLE_API_KEY)
config = types.GenerateContentConfig(
    system_instruction="Act like a useful assistant",
    temperature=1,
    top_p=0.95,
    top_k=40,
    candidate_count=1,
    seed=-1,
    max_output_tokens=8192,
    safety_settings=[
        types.SafetySetting(category='HARM_CATEGORY_HATE_SPEECH', threshold='BLOCK_NONE'),
        types.SafetySetting(category='HARM_CATEGORY_HARASSMENT', threshold='BLOCK_NONE'),
        types.SafetySetting(category='HARM_CATEGORY_SEXUALLY_EXPLICIT', threshold='BLOCK_NONE'),
        types.SafetySetting(category='HARM_CATEGORY_DANGEROUS_CONTENT', threshold='BLOCK_NONE')
    ],
    tools=[
        types.Tool(code_execution={}),
    ]
)

```

Using Files to send the image with the text prompt in the chat session
```
async def main():
    chat = client.aio.chats.create(
    model="models/gemini-2.0-flash-exp",
    config=config,
    history=[]
    )
    path = "...../uuu.jpg"
    file = client.files.upload(path=path)
    file_uri = file.uri  # Get the URI from the file object
    mime_type = file.mime_type  # Get the mime_type from the file object
    media_file = types.Part.from_uri(file_uri=file_uri, mime_type=mime_type)
    print("--------------")

    await asyncio.sleep(10) #Waiting manually to make sure file is active before processing
    response = await chat.send_message(["What do you think of this?",media_file])
    
    print(media_file.file_data.file_uri) #prints the file_uri
    print(await extract_response_text(response)) #custom function for printing out the final response

```
Using local upload to send the image with the text prompt in the chat session
```
async def main():
    chat = client.aio.chats.create(
    model="models/gemini-2.0-flash-exp",
    config=config,
    history=[]
    )
    path = "...../uuu.jpg"

    with open(path, 'rb') as f:
        image_bytes = f.read()

    format="image/jpeg"
    media_file = types.Part.from_bytes(
                    data=image_bytes,
                    mime_type=format
                )
    print("--------------")
    #await asyncio.sleep(10)
    
    response = await chat.send_message(["What do you think of this?",media_file])


    #print(media_file.file_data.file_uri)
    print(await extract_response_text(response))

```

**Comment by Giom-V** [comment]
Hello @War004, I cannot see any major difference with what we recommend to do in the [Cookbook getting starting notebook](https://colab.sandbox.google.com/github/google-gemini/cookbook/blob/main/gemini-2/get_started.ipynb#scrollTo=zGswPFKrTvby), so could you share the image you are using, maybe there's an issue with it?

**Comment by War004** [comment]
* The issue was arising with any image I used; I even checked the sha 256 hash generated through in the files Api and in my local machine. 
* ~~It's unstable right now, will update after some hours.~~ ~~But right now, the issue seems to be fixed when using the files Api, **as of now I still get the same error when I directly send the images.~~**
* ~~Removing the code execution in the tools eliminated all the issues.~~

~~# Now the issue is solved.~~

**Comment by War004** [comment]
Hey @Giom-V seems like the bug is back, the trigger is same as before, sending image file into the chat session. 
Directly uploading to chat or using files Api result in 400 error. 
```
ClientError                               Traceback (most recent call last)
<ipython-input-61-ad5a03c9c4d7> in <cell line: 0>()
      2 print(f"{current_time}\nSecond run for direct")
      3 if __name__ == "__main__":
----> 4     asyncio.run(main())

17 frames
/usr/local/lib/python3.11/dist-packages/google/genai/errors.py in raise_for_response(cls, response)
     98     status_code = response.status_code
     99     if 400 <= status_code < 500:
--> 100       raise ClientError(status_code, response)
    101     elif 500 <= status_code < 600:
    102       raise ServerError(status_code, response)

ClientError: 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Request contains an invalid argument.', 'status': 'INVALID_ARGUMENT'}}
```
* Additionally, while using local upload, it is not able to process the video file and the images. Audio files are working. 
* In files api just image files are not processed just as before. 

Here is a notebook that I am using for testing

https://colab.research.google.com/drive/1kRvaQ7KbJ3bu0BnKu1rWNxv-vF8t18IR#scrollTo=mPL9i0Qhr49O

**Comment by Giom-V** [comment]
@War004 Thanks for the notebook. I think there's an issue with the chat mode that doesn't seem to handle images at the moment. I think you should use single calls like shown [here](https://colab.sandbox.google.com/github/google-gemini/cookbook/blob/main/gemini-2/get_started.ipynb#scrollTo=yww-vrxmRiIy) or the previous SDK for the moment as the new SDK is still in its early stages.

**Comment by Giom-V** [comment]
@War004 I got it to work with this code:
```
!wget "https://storage.googleapis.com/generativeai-downloads/data/jetpack.png" -O jetpack.png -q
image = Image.open('jetpack.png')
image_upload = client.files.upload(path='jetpack.png')

response = chat.send_message([
    "What is this?",
    types.Part.from_uri(
      file_uri=image_upload.uri,
      mime_type=image_upload.mime_type),
    ])
```
